name: tokosmile
description: Implementation of the Tokosmile concept on Dribbble, done in Flutter.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-Bold.ttf
          weight: 700

  assets:
    - images/carousel_1.png
    - images/carousel_2.png
    - images/product_1.jpg
    - images/product_2.jpg
    - images/product_3.jpg
    - images/product_4.jpg
    - images/product_5.jpg
    - images/bag_1.jpg
    - images/bag_2.jpg
    - images/bag_3.jpg
    - images/bag_4.jpg
